name: 打包msykanswer.py为exe

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: 安装python环境
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: 安装requirements.txt
        run: pip install -r requirements.txt

      - name: 安装pyinstaller
        run: pip install pyinstaller
        
      - name: 显示目录
        run: pwd

      - name: 下载图标
        run: iwr -Uri "https://files.catbox.moe/3pn1da.ico" -OutFile "icon.ico"

      - name: 打包
        run: pyinstaller -F -i ./icon.ico ./msykanswer.py

      - name: 上传Artifact
        uses: actions/upload-artifact@v2
        with:
          name: msykanswer
          path: dist/
          
      - name: 自带生成更新文档
        run: write-output "CHANGELOG:${{ github.event.head_commit.message }}" | out-file -filepath ./CHANGELOG.txt
        
      - name: 上传Release
        uses: ncipollo/release-action@v1.8.0
        with:
          artifacts: "./dist/*"
          tag: ver-${{ github.sha }}
          bodyFile: "./CHANGELOG.txt"
          token: ${{ secrets.GITHUB_TOKEN }}